openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description:
    This is a documentation of contacts app
tags:
  - name: Contacts
    description: Operations about contacts.
  - name: Users
    description: Users operations.
servers:
  - url: https://contacts-api-ccs8.onrender.com
paths:
  /contacts:
    get:
      $ref: ../swagger/paths/contacts/get.yaml
    post:
      $ref: ../swagger/paths/contacts/post.yaml
  /contacts/{contactId}:
    patch:
      $ref: ../swagger/paths/contacts/{contactId}/patch.yaml
    delete:
      $ref: ../swagger/paths/contacts/{contactId}/delete.yaml
  /users/signup:
    post:
      $ref: ../swagger/paths/users/signUp.yaml
  /users/login:
    post:
      $ref: ../swagger/paths/users/login.yaml
  /users/logout:
    post:
      $ref: ../swagger/paths/users/logout.yaml
  /users/current:
    post:
      $ref: ../swagger/paths/users/current.yaml
  /users/send-reset-email:
    post:
      $ref: ../swagger/paths/users/sendResetEmail.yaml
  /users/reset-pwd:
    post:
      $ref: ../swagger/paths/users/resetPwd.yaml
  /users/get-oauth-url:
    get:
      $ref: ../swagger/paths/users/getOAuthUrl.yaml
  /users/confirm-oauth:
    post:
      $ref: ../swagger/paths/users/confirmOAuth.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
